#!/bin/bash

# Teacher Authentication API - cURL Test Examples
# This script provides working cURL commands for testing all authenticated endpoints

BASE_URL="http://localhost/amt/api/teacher"
EMAIL="mahalakshmisalla70@gmail.com"
PASSWORD="testpass123"

echo "Teacher Authentication API - cURL Test Examples"
echo "==============================================="
echo ""

# Step 1: Login to get authentication token
echo "1. LOGIN"
echo "--------"
echo "curl -X POST \"$BASE_URL/login\" \\"
echo "  -H \"Client-Service: smartschool\" \\"
echo "  -H \"Auth-Key: schoolAdmin@\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"email\":\"$EMAIL\",\"password\":\"$PASSWORD\"}'"
echo ""

# Get the token (you'll need to replace these with actual values from login response)
echo "# After login, extract the token and user_id from the response:"
echo "# TOKEN=\"your_actual_token_here\""
echo "# USER_ID=\"your_actual_user_id_here\""
echo ""

TOKEN="REPLACE_WITH_ACTUAL_TOKEN"
USER_ID="REPLACE_WITH_ACTUAL_USER_ID"

echo "2. PROFILE ENDPOINT (Header Authentication)"
echo "-------------------------------------------"
echo "curl -X GET \"$BASE_URL/profile\" \\"
echo "  -H \"Client-Service: smartschool\" \\"
echo "  -H \"Auth-Key: schoolAdmin@\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -H \"User-ID: $USER_ID\" \\"
echo "  -H \"Authorization: $TOKEN\""
echo ""

echo "3. PROFILE ENDPOINT (JSON Body Authentication)"
echo "----------------------------------------------"
echo "curl -X GET \"$BASE_URL/profile\" \\"
echo "  -H \"Client-Service: smartschool\" \\"
echo "  -H \"Auth-Key: schoolAdmin@\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"user_id\":\"$USER_ID\",\"token\":\"$TOKEN\"}'"
echo ""

echo "4. STAFF DETAILS BY ID (Header Authentication)"
echo "----------------------------------------------"
echo "curl -X GET \"$BASE_URL/staff/1\" \\"
echo "  -H \"Client-Service: smartschool\" \\"
echo "  -H \"Auth-Key: schoolAdmin@\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -H \"User-ID: $USER_ID\" \\"
echo "  -H \"Authorization: $TOKEN\""
echo ""

echo "5. STAFF SEARCH (Header Authentication)"
echo "---------------------------------------"
echo "curl -X GET \"$BASE_URL/staff-search?search=teacher&limit=5&offset=0\" \\"
echo "  -H \"Client-Service: smartschool\" \\"
echo "  -H \"Auth-Key: schoolAdmin@\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -H \"User-ID: $USER_ID\" \\"
echo "  -H \"Authorization: $TOKEN\""
echo ""

echo "6. STAFF BY ROLE (Header Authentication)"
echo "----------------------------------------"
echo "curl -X GET \"$BASE_URL/staff-by-role/1?is_active=1\" \\"
echo "  -H \"Client-Service: smartschool\" \\"
echo "  -H \"Auth-Key: schoolAdmin@\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -H \"User-ID: $USER_ID\" \\"
echo "  -H \"Authorization: $TOKEN\""
echo ""

echo "7. STAFF BY EMPLOYEE ID (Header Authentication)"
echo "-----------------------------------------------"
echo "curl -X GET \"$BASE_URL/staff-by-employee-id/EMP001\" \\"
echo "  -H \"Client-Service: smartschool\" \\"
echo "  -H \"Auth-Key: schoolAdmin@\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -H \"User-ID: $USER_ID\" \\"
echo "  -H \"Authorization: $TOKEN\""
echo ""

echo "8. LOGOUT (JSON Body Authentication)"
echo "------------------------------------"
echo "curl -X POST \"$BASE_URL/logout\" \\"
echo "  -H \"Client-Service: smartschool\" \\"
echo "  -H \"Auth-Key: schoolAdmin@\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"user_id\":\"$USER_ID\",\"token\":\"$TOKEN\",\"deviceToken\":\"test_device_token\"}'"
echo ""

echo "AUTOMATED TEST EXECUTION"
echo "========================"
echo ""
echo "To run automated tests:"
echo "1. PHP Script: php api/test_scripts/test_teacher_auth_endpoints.php"
echo "2. PowerShell: powershell -ExecutionPolicy Bypass -File api/test_scripts/test_teacher_auth_endpoints.ps1"
echo ""

echo "NOTES:"
echo "------"
echo "1. Replace TOKEN and USER_ID with actual values from login response"
echo "2. All GET endpoints support header-based authentication"
echo "3. POST endpoints (like logout) support JSON body authentication"
echo "4. The hybrid authentication system supports both methods for all endpoints"
echo "5. Required headers for all requests:"
echo "   - Client-Service: smartschool"
echo "   - Auth-Key: schoolAdmin@"
echo "   - Content-Type: application/json"
echo ""

echo "TROUBLESHOOTING:"
echo "----------------"
echo "1. If you get 401 Unauthorized:"
echo "   - Check if login was successful and token is valid"
echo "   - Verify User-ID and Authorization headers are correct"
echo "   - Ensure Client-Service and Auth-Key headers are present"
echo ""
echo "2. If you get 400 Bad Request:"
echo "   - Check request method (GET vs POST)"
echo "   - Verify required parameters are provided"
echo "   - Check JSON format for POST requests"
echo ""
echo "3. If you get 404 Not Found:"
echo "   - Verify the endpoint URL is correct"
echo "   - Check if the resource (staff ID, employee ID, etc.) exists"
echo ""
